services:
  - type: worker
    name: fiqo-signal-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8415870832:AAHlVaoQ-KJdr1JlyCbzwYap7g9RRtNsSgsew"
      - key: CHAT_ID
        value: "904917014"
      - key: EXCHANGE
        value: "binance"
      - key: SYMBOLS
        value: "ETH/USDT,BTC/USDT"
      - key: TIMEFRAMES
        value: "15m,1h"
      - key: MIN_CONF
        value: "60"
      - key: SL
        value: "45"
      - key: LIMIT
        value: "200"
